-- Create the products table
CREATE TABLE products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  image text,
  category text,
  sizes text[],
  colors text[]
);
